package com.gremier.gkeys.ime.touch

import android.content.Context
import kotlin.math.roundToLong
import kotlin.random.Random

object SwipeTestRunner {
    val testWords: List<String> = listOf(
        "the", "that", "this", "there", "with", "want", "need", "make", "take", "give", "help",
        "tool", "toolbox", "good", "coffee", "book", "look", "soon",
        "keyboard", "delivery", "settings", "message", "remember", "important", "different",
        "because", "probably", "actually",
        "Gremier", "Supabase", "Codex", "PayMe", "OpenAI", "Shabbos", "yeshiva", "coldbrew",
        "that's", "don't", "can't", "won't", "I'm", "you're", "it's",
        "that", "thats", "that's", "theater",
        "there", "their", "they're",
        "your", "you're",
        "its", "it's",
    )

    fun run(
        context: Context,
        repeatsPerWord: Int = 4,
        noisePx: Float = 4f,
    ): SwipeTestReport {
        val learningStore = SwipeLearningStore(context)
        val engine = AospGestureTypingEngine(context, learningStore)
        val targets = qwertyTargets()
        val userWords = testWords.associate { it.lowercase() to 40 }
        engine.updateGeometry(720, 260, targets)
        engine.ensureDictionary(userWords, maxSystemWords = 24_000)
        val cases = ArrayList<SwipeTestCaseResult>()
        for (word in testWords.distinct()) {
            val runs = (0 until repeatsPerWord).map { runIndex ->
                val path = idealPathFor(word, targets, noisePx, seed = word.hashCode() * 31 + runIndex)
                val diagnostics = engine.diagnose(
                    points = path,
                    userWords = userWords,
                    previousWord = "",
                    nextWord = null,
                    targetWord = word,
                )
                val rank = diagnostics.targetRank
                SwipeTestRunResult(
                    rank = rank,
                    generated = diagnostics.targetGeneratedAsRawCandidate,
                    reason = reasonFor(word, diagnostics),
                    diagnostics = diagnostics,
                )
            }
            cases += SwipeTestCaseResult(word, runs)
        }
        engine.close()
        return SwipeTestReport(cases)
    }

    fun format(report: SwipeTestReport): String = buildString {
        appendLine("Swipe accuracy report")
        appendLine("top3=${report.top3Passes}/${report.totalRuns} top5=${report.top5Passes}/${report.totalRuns} top10=${report.top10Passes}/${report.totalRuns}")
        report.cases.forEach { case ->
            val bestRank = case.runs.mapNotNull { it.rank }.minOrNull()
            val generated = case.runs.any { it.generated }
            val top10 = case.runs.any { (it.rank ?: Int.MAX_VALUE) <= 10 }
            append(case.word)
            append(": generated=").append(if (generated) "yes" else "no")
            append(", top10=").append(if (top10) "yes" else "no")
            append(", rank=").append(bestRank ?: "missing")
            case.runs.firstOrNull { (it.rank ?: Int.MAX_VALUE) > 10 }?.reason?.let {
                append(", reason=").append(it)
            }
            appendLine()
        }
    }

    private fun reasonFor(word: String, diagnostics: SwipeDiagnostics): String =
        diagnostics.targetRemovedBy
            ?: diagnostics.failureReason
            ?: when {
                !diagnostics.targetInDictionary -> "not in swipe dictionary"
                !diagnostics.targetGeneratedAsRawCandidate -> "not generated by candidate filters"
                word.zipWithNext().any { it.first.equals(it.second, ignoreCase = true) } -> "repeated-letter ranking needs review"
                '\'' in word -> "apostrophe/contraction ranking needs review"
                else -> "ranked below top candidates"
            }

    private fun idealPathFor(
        word: String,
        targets: List<KeyHitTarget>,
        noisePx: Float,
        seed: Int,
    ): List<SwipePoint> {
        val byChar = targets.associateBy { it.char }
        val points = ArrayList<SwipePoint>()
        val random = Random(seed)
        val letters = word.lowercase().filter { it.isLetter() }.fold(StringBuilder()) { acc, char ->
            if (acc.lastOrNull() != char) acc.append(char)
            acc
        }.toString()
        var time = 0L
        letters.forEachIndexed { index, char ->
            val target = byChar[char] ?: return@forEachIndexed
            val prev = if (index == 0) target else byChar[letters[index - 1]] ?: target
            val steps = if (index == 0) 1 else 5
            for (step in 0 until steps) {
                val t = if (steps == 1) 1f else step.toFloat() / (steps - 1)
                points += SwipePoint(
                    x = prev.centerX + (target.centerX - prev.centerX) * t + randomNoise(random, noisePx),
                    y = prev.centerY + (target.centerY - prev.centerY) * t + randomNoise(random, noisePx),
                    timeMs = time,
                )
                time += 12L
            }
        }
        return points
    }

    private fun randomNoise(random: Random, noisePx: Float): Float =
        ((random.nextDouble() * 2.0 - 1.0) * noisePx).toFloat()

    private fun qwertyTargets(): List<KeyHitTarget> {
        val key = 60f
        val rows = listOf(
            "qwertyuiop" to 0f,
            "asdfghjkl" to 30f,
            "zxcvbnm" to 90f,
        )
        val out = ArrayList<KeyHitTarget>()
        rows.forEachIndexed { rowIndex, row ->
            val y = 40f + rowIndex * 70f
            row.first.forEachIndexed { index, char ->
                val x = row.second + 40f + index * key
                out += KeyHitTarget(
                    label = char.toString(),
                    char = char,
                    row = rowIndex,
                    centerX = x,
                    centerY = y,
                    width = key,
                    height = key,
                    sweetSpotX = x,
                    sweetSpotY = y,
                )
            }
        }
        return out
    }
}

data class SwipeTestReport(
    val cases: List<SwipeTestCaseResult>,
) {
    val totalRuns: Int get() = cases.sumOf { it.runs.size }
    val top3Passes: Int get() = cases.sumOf { case -> case.runs.count { (it.rank ?: Int.MAX_VALUE) <= 3 } }
    val top5Passes: Int get() = cases.sumOf { case -> case.runs.count { (it.rank ?: Int.MAX_VALUE) <= 5 } }
    val top10Passes: Int get() = cases.sumOf { case -> case.runs.count { (it.rank ?: Int.MAX_VALUE) <= 10 } }
}

data class SwipeTestCaseResult(
    val word: String,
    val runs: List<SwipeTestRunResult>,
)

data class SwipeTestRunResult(
    val rank: Int?,
    val generated: Boolean,
    val reason: String,
    val diagnostics: SwipeDiagnostics,
)
